# TP3: Large Scale Graph Learning

Student: Pierre-Louis Guhur (pierre-louis.guhur@ens-paris-saclay.fr)


***Question 1:* Complete online_ssl_update_centroids using the pseudo code from 1.**

In [5]:
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from Online_SSL.func import *
from Large_Scale_Label_Propagation.func import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
create_user_profile("Antonin", "data")

Profile found with 19 images.


In [3]:
online_face_recognition(["Raphael", "PL", "Antonin"])

Profile found with 16 images.
Profile found with 10 images.
Profile found with 19 images.
[s]ave a frame ?


# 3. Large Scale Label Propagation

In [6]:
iterative_hfs()

100%|██████████| 20/20 [06:14<00:00, 18.71s/it]

[1 1 1 ... 2 2 2]
[[2.]
 [1.]
 [1.]
 ...
 [2.]
 [2.]
 [1.]]


(array([1, 1, 1, ..., 2, 2, 2]), 0.9504)